<a href="https://colab.research.google.com/github/psssnikhil/DeepLearning-with-pytorch/blob/master/Understanding_Gradient_descent_and_implementation_of_Linear_Regressionn_using_PyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch


Once the Torch is imported.Now let us inout some data.ie suppose if in linear regression the equation y1=w11*x1+w12*x2+w13*x3+b1 and y2=w21*x1+w22*x2+w23*x3+b2 ie we are finding the independent variable using the dependent variables like x1,x2,x3 which are the inputs to the model.

In [0]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [70]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [71]:
#its time to assign weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.1709,  0.0519, -0.4027],
        [-1.0139,  1.1941, -0.3791]], requires_grad=True)
tensor([2.5182, 0.1430], requires_grad=True)


In [0]:
def model(x):
  return x @ w.t()+b

In [73]:
preds=model(inputs)
print(targets)
print(preds)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[-23.7982, -10.1698],
        [-34.2419, -11.3059],
        [-28.7524,  49.9518],
        [-27.5857, -65.9550],
        [-32.4821,  18.2771]], grad_fn=<AddBackward0>)


In [0]:
#Taking mse
def mse(targets,preds):
  diff=targets-preds
  diff_sqr=diff**2
  return torch.sum(diff_sqr)/diff_sqr.numel()

In [75]:
loss=mse(targets,preds)
print(loss)

tensor(10897.4980, grad_fn=<DivBackward0>)


In [0]:
loss.backward()

In [77]:
print(w)
print(w.grad)

tensor([[-0.1709,  0.0519, -0.4027],
        [-1.0139,  1.1941, -0.3791]], requires_grad=True)
tensor([[ -8714.5479, -10085.0098,  -6138.9717],
        [ -8149.7427,  -8095.8423,  -5262.3223]])


In [78]:
print(b)
print(b.grad)

tensor([2.5182, 0.1430], requires_grad=True)
tensor([-105.5720,  -95.8403])


In [79]:
#now let us reset the Gradients
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [80]:
preds=model(inputs)
print(preds)

tensor([[-23.7982, -10.1698],
        [-34.2419, -11.3059],
        [-28.7524,  49.9518],
        [-27.5857, -65.9550],
        [-32.4821,  18.2771]], grad_fn=<AddBackward0>)


In [81]:
loss=mse(targets,preds)
print(loss)

tensor(10897.4980, grad_fn=<DivBackward0>)


In [82]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -8714.5479, -10085.0098,  -6138.9717],
        [ -8149.7427,  -8095.8423,  -5262.3223]])
tensor([-105.5720,  -95.8403])


In [83]:
print(w)
print(b)

tensor([[-0.1709,  0.0519, -0.4027],
        [-1.0139,  1.1941, -0.3791]], requires_grad=True)
tensor([2.5182, 0.1430], requires_grad=True)


In [0]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()


In [85]:
print(w.grad)
print(b.grad)
print(w)
print(b)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])
tensor([[-0.0838,  0.1528, -0.3413],
        [-0.9324,  1.2750, -0.3265]], requires_grad=True)
tensor([2.5193, 0.1440], requires_grad=True)


In [86]:
print(targets)
print(preds)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[-23.7982, -10.1698],
        [-34.2419, -11.3059],
        [-28.7524,  49.9518],
        [-27.5857, -65.9550],
        [-32.4821,  18.2771]], grad_fn=<AddBackward0>)


In [87]:
preds=model(inputs)
loss=mse(targets,preds)
print(loss)

tensor(7482.8018, grad_fn=<DivBackward0>)


In [0]:
for i in range(100):
  preds=model(inputs)
  loss=mse(targets,preds)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [89]:
preds=model(inputs)
loss=mse(targets,preds)
print(loss)

tensor(171.3008, grad_fn=<DivBackward0>)


In [91]:
print(preds)
print(targets)

tensor([[ 61.4157,  68.3020],
        [ 79.8556,  91.2246],
        [117.2152, 157.6678],
        [ 42.8082,  24.3893],
        [ 85.6484, 110.1032]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


HOLA they are close enough.Let us Now sumup everythin by learning linear regression implementation

In [0]:
import torch.nn as nn

In [0]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [0]:
from torch.utils.data import TensorDataset

In [0]:
train_ds=TensorDataset(inputs,targets)


In [97]:
train_ds[0:4]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

In [0]:
from torch.utils.data import DataLoader

In [99]:
#define dataloader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)
print(train_dl)

In [101]:
for xb,yb in train_dl:
  print('start of batch')
  print(xb)
  print(yb)
  print('End of batch')

start of batch
tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[119., 133.],
        [103., 119.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.]])
End of batch
start of batch
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.]])
End of batch
start of batch
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 56.,  70.],
        [ 81., 101.]])
End of batch


In [102]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.1624, -0.4321,  0.0249],
        [ 0.4883, -0.2916, -0.0461]], requires_grad=True)
Parameter containing:
tensor([0.1778, 0.3968], requires_grad=True)


In [103]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1624, -0.4321,  0.0249],
         [ 0.4883, -0.2916, -0.0461]], requires_grad=True),
 Parameter containing:
 tensor([0.1778, 0.3968], requires_grad=True)]

In [104]:
preds=model(inputs)
preds

tensor([[-39.5525,  14.5201],
        [-51.0252,  16.2167],
        [-70.4008,   1.1256],
        [-34.0413,  35.9561],
        [-50.7598,   2.8647],
        [-39.5525,  14.5201],
        [-51.0252,  16.2167],
        [-70.4008,   1.1256],
        [-34.0413,  35.9561],
        [-50.7598,   2.8647],
        [-39.5525,  14.5201],
        [-51.0252,  16.2167],
        [-70.4008,   1.1256],
        [-34.0413,  35.9561],
        [-50.7598,   2.8647]], grad_fn=<AddmmBackward>)

In [0]:
import torch.nn.functional as F

In [0]:
loss_fn=F.mse_loss

In [108]:
loss=loss_fn(preds,targets)
print(loss)

tensor(13036.1865, grad_fn=<MseLossBackward>)


In [0]:
#definiing optimizer which manipulates the weights and biases using gradients automatically
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [0]:
from tqdm import tqdm

def fit(num_epochs,model,loss_fn,opt):
  for epoch in tqdm(range(num_epochs)):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1)%10==0:

      print('Epoch [{},{}],Loss : {:.4f}'.format(epoch+1,num_epochs,loss.item()))  

In [121]:
fit(100,model,loss_fn,opt)

100%|██████████| 100/100 [00:00<00:00, 756.11it/s]

Epoch [10,100],Loss : 3.2155
Epoch [20,100],Loss : 1.6150
Epoch [30,100],Loss : 1.7290
Epoch [40,100],Loss : 2.1081
Epoch [50,100],Loss : 1.1115
Epoch [60,100],Loss : 1.7043
Epoch [70,100],Loss : 1.3115
Epoch [80,100],Loss : 1.2176
Epoch [90,100],Loss : 1.4318
Epoch [100,100],Loss : 1.5486


In [122]:
preds=model(inputs)
preds

tensor([[ 57.2441,  70.4820],
        [ 81.9692,  99.8337],
        [119.2279, 134.6371],
        [ 21.2410,  37.4979],
        [101.4404, 117.4752],
        [ 57.2441,  70.4820],
        [ 81.9692,  99.8337],
        [119.2279, 134.6371],
        [ 21.2410,  37.4979],
        [101.4404, 117.4752],
        [ 57.2441,  70.4820],
        [ 81.9692,  99.8337],
        [119.2279, 134.6371],
        [ 21.2410,  37.4979],
        [101.4404, 117.4752]], grad_fn=<AddmmBackward>)

In [123]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Here we go.Got the predicitons so closely.u can try out few things if you want.
1)Use diff optimizer like Adam etc.
2)change numbers of inputs and see
3)change the LR
4)increase number of epochs
5)manipulate or write your own loss function